BIN = bryton860-core
DESTDIR ?= /usr/bin

SRC = src/main.c

# Include Wayland XDG protocol file generated by lv-drivers lib
SRC += $(SYSROOT)/usr/include/lvgl/lv_drivers/wayland/protocols/wayland-xdg-shell-client-protocol.c

INCLUDE = -Isrc \
          -I$(SYSROOT)/usr/include/lvgl \
          -I$(SYSROOT)/usr/include/lvgl/lv_drivers \
          -I$(SYSROOT)/usr/include/lvgl/lv_drivers/wayland

LVGL_LIB_PATH ?= $(SYSROOT)/usr/lib/liblvgl.a
LV_DRIVERS_LIB_PATH ?= $(SYSROOT)/usr/lib/liblv_drivers.a

CC ?= gcc
CCLD ?= gcc

CFLAGS += $(INCLUDE)
LDFLAGS += $(LVGL_LIB_PATH) $(LV_DRIVERS_LIB_PATH) -lwayland-client -lxkbcommon -lwayland-cursor -lpthread

OBJS = $(patsubst %.c, %.o, $(SRC))

all: $(BIN)

%.o : %.c
	@echo "BUILD: $(CC) -c $(CFLAGS) $< -o $@"
	$(CC) -c $(CFLAGS) $< -o $@

$(BIN): $(OBJS)
	@echo "LINK: $(CCLD) $(LDFLAGS) -o $@ $^"
	$(CCLD) $(OBJS) $(LDFLAGS) -o $(BIN)

install:
	install -D $(BIN) $(DESTDIR)/$(BIN)

clean:
	rm -f $(OBJS) $(BIN)

.PHONY: all clean
